import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Navbar} from '../app/components/Navbar'
// import Navbar from '../app/components/Navbar'

const inter = Inter({ subsets: ["latin"] });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Mently",
  description: "Mently",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <div className="lg:flex flex  ">
        {/* <div className="lg:w-[298px] lg:h-[1024px] lg:gap-[24px] lg:border-t-[0px] lg-border-r-[0.5px] lg:border-b-[0px] lg:border-l-[0px] hidden md:block lg:block "> */}
          <div className="lg:w-[7000px] lg:h-[1168px] lg:gap-[24px] lg:border-t-[0px] lg-border-r-[0.5px] lg:border-b-[0px]
           lg:border-l-[0px] hidden md:block lg:block lg:bg-indigo-300">
          {/* width: 240;
height: 1168; */}

            <Navbar />
          </div>
          <div className="">
          {children}
          </div>
        </div>
        </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
